Repository marvinIsSacul/mylms-timetable-plus, pull requests merged in 2023-06, with the labels that each got.

#1 Feature/wip
  .gitignore
  README.md
  jest.config.ts
  package-lock.json
  package.json
  public/icon-128.png
  public/icon-16.png
  public/icon-32.png
  public/icon-48.png
  public/manifest.json
  public/popup.html
  public/popup.ts
  src/background.ts
  src/content.ts
  test/content.test.ts
  tsconfig.json
  webpack/webpack.config.js
Labels: enhancement

#2 reference local license file instead of third party link
  .eslintignore
  .eslintrc.js
  .github/workflows/build.yml
  CONTRIBUTING.md
  README.md
  jest.config.ts
  package-lock.json
  package.json
  public/popup.ts
  src/content.ts
  test/content.test.ts
  tsconfig.json
Labels: documentation, enhancement

#3 chore: remove unused permissions.
  public/manifest.json
Labels: bug

#6 Adding missing assets
  public/assets/bootstrap.min.js
  public/assets/jquery-3.2.1.slim.min.js
  public/assets/popper.min.js
Labels: bug
